In [16]:
import pandas as pd
import re

# Load your DataFrame
df = pd.read_csv('NejashMarket.csv')

In [17]:
df

,message_id,from_id,date,message_text
0,13059,NaN,2024-09-28 14:06:43+00:00,❇️High pressure water Gun nozzle\n\n 🔰መኪና ለማ...
1,13058,NaN,2024-09-28 13:26:43+00:00,👆👆 ገብቷል ውስን ፍሬ ይፍጠኑ\n\n👉 ቤቶ ሁነው የተለያዩ ስራዎችን እ...
2,13057,NaN,2024-09-28 09:15:17+00:00,👆 ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስ...
3,13056,NaN,2024-09-27 11:16:28+00:00,👆 ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስ...
4,13055,NaN,2024-09-26 10:53:59+00:00,👆 ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስ...
...,...,...,...,...
6263,6412,NaN,2021-10-12 11:55:20+00:00,NaN
6264,6411,NaN,2021-10-12 11:55:20+00:00,Kitchen Oil proof Stickers\nለኪችንዎ ግርማሞገስ የሚያላብ...
6265,6410,NaN,2021-10-12 11:55:20+00:00,NaN
6266,6409,NaN,2021-10-12 11:55:18+00:00,💢የልጆች መማሪያ ታብሌት\n\nTelegram : 👇👇👇\n https://t....
6267,1,NaN,2019-10-24 09:34:03+00:00,NaN

In [18]:
print("Checking for NaN values in the 'Message' column:")
nan_count = df['message_text'].isnull().sum()
print(f"Number of NaN values in 'Message' column: {nan_count}")

Checking for NaN values in the 'Message' column:
Number of NaN values in 'Message' column: 1875

In [19]:
df = df.dropna(subset=['message_text'])

# Print the shape of the dataset after dropping NaN values in the "Message" column
print(f"Dataset shape after dropping NaN values in 'Message' column: {df.shape}")

Dataset shape after dropping NaN values in 'Message' column: (4393, 4)

In [20]:
df.head()

,message_id,from_id,date,message_text
0,13059,NaN,2024-09-28 14:06:43+00:00,❇️High pressure water Gun nozzle\n\n 🔰መኪና ለማ...
1,13058,NaN,2024-09-28 13:26:43+00:00,👆👆 ገብቷል ውስን ፍሬ ይፍጠኑ\n\n👉 ቤቶ ሁነው የተለያዩ ስራዎችን እ...
2,13057,NaN,2024-09-28 09:15:17+00:00,👆 ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስ...
3,13056,NaN,2024-09-27 11:16:28+00:00,👆 ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስ...
4,13055,NaN,2024-09-26 10:53:59+00:00,👆 ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስ...

In [21]:
message_df=df['message_text']
message_df

0       ❇️High pressure water Gun nozzle\n\n   🔰መኪና ለማ...
1       👆👆  ገብቷል ውስን ፍሬ ይፍጠኑ\n\n👉 ቤቶ ሁነው የተለያዩ ስራዎችን እ...
2       👆 ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስ...
3       👆 ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስ...
4       👆 ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስ...
                              ...
6260    Smiling foot protector \n390 birr \nE020 \nእጃች...
6261    👆 ለቤቶ ለስራ ቦታዎ ምርጥ የሴራሚክ መጥረጊያ ማሽኝ\n\n\nTelegra...
6262      Kitchen Oil proof Stickers\nለኪችንዎ ግርማሞገስ የሚያላብስ
6264    Kitchen Oil proof Stickers\nለኪችንዎ ግርማሞገስ የሚያላብ...
6266    💢የልጆች መማሪያ ታብሌት\n\nTelegram : 👇👇👇\n https://t....
Name: message_text, Length: 4393, dtype: object

In [22]:
# Define a function to remove emojis
def remove_emojis(text):
    # Check if the input is a string before processing
    if isinstance(text, str):
        emoji_pattern = re.compile(
            "[" 
            "\U0001F600-\U0001F64F"  # emoticons
            "\U0001F300-\U0001F5FF"  # symbols & pictographs
            "\U0001F680-\U0001F6FF"  # transport & map symbols
            "\U0001F700-\U0001F77F"  # alchemical symbols
            "\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
            "\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
            "\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
            "\U0001FA00-\U0001FA6F"  # Chess Symbols
            "\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
            "\U00002702-\U000027B0"  # Dingbats
            "\U000024C2-\U0001F251" 
            "]+", 
            flags=re.UNICODE
        )
        return emoji_pattern.sub(r'', text)
    else:
        return text  # Return non-string values as is (could also use '' if you want empty strings)

# Apply the function to the 'message_text' column
df['message_text'] = df['message_text'].apply(remove_emojis)

# Display the updated DataFrame
print(df.head())

   message_id  from_id                       date  \
0       13059      NaN  2024-09-28 14:06:43+00:00
1       13058      NaN  2024-09-28 13:26:43+00:00
2       13057      NaN  2024-09-28 09:15:17+00:00
3       13056      NaN  2024-09-27 11:16:28+00:00
4       13055      NaN  2024-09-26 10:53:59+00:00

                                        message_text
0  High pressure water Gun nozzle\n\n   መኪና ለማጠብ\...
1    ገብቷል ውስን ፍሬ ይፍጠኑ\n\n ቤቶ ሁነው የተለያዩ ስራዎችን እየሰሩ...
2   ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስቀ...
3   ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስቀ...
4   ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስቀ...

C:\Users\HP\AppData\Local\Temp\ipykernel_32172\104043281.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['message_text'] = df['message_text'].apply(remove_emojis)

In [23]:
df

,message_id,from_id,date,message_text
0,13059,NaN,2024-09-28 14:06:43+00:00,High pressure water Gun nozzle\n\n መኪና ለማጠብ\...
1,13058,NaN,2024-09-28 13:26:43+00:00,ገብቷል ውስን ፍሬ ይፍጠኑ\n\n ቤቶ ሁነው የተለያዩ ስራዎችን እየሰሩ...
2,13057,NaN,2024-09-28 09:15:17+00:00,ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስቀ...
3,13056,NaN,2024-09-27 11:16:28+00:00,ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስቀ...
4,13055,NaN,2024-09-26 10:53:59+00:00,ወርቃማው የሲኒ ረከቦት\n\n4 in 1 የጀበና ማስቀመጫ፣ የስኳን ማስቀ...
...,...,...,...,...
6260,6415,NaN,2021-10-12 11:55:20+00:00,Smiling foot protector \n390 birr \nE020 \nእጃች...
6261,6414,NaN,2021-10-12 11:55:20+00:00,ለቤቶ ለስራ ቦታዎ ምርጥ የሴራሚክ መጥረጊያ ማሽኝ\n\n\nTelegram...
6262,6413,NaN,2021-10-12 11:55:20+00:00,Kitchen Oil proof Stickers\nለኪችንዎ ግርማሞገስ የሚያላብስ
6264,6411,NaN,2021-10-12 11:55:20+00:00,Kitchen Oil proof Stickers\nለኪችንዎ ግርማሞገስ የሚያላብ...
6266,6409,NaN,2021-10-12 11:55:18+00:00,የልጆች መማሪያ ታብሌት\n\nTelegram : \n https://t.me/n...

In [24]:
df.to_csv('clean_data.csv')